apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      service: reverseproxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: saik4t/reverseproxy
        imagePullPolicy: Always
        name: reverseproxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 0.1
            memory: 1024Mi
          requests:
            cpu: 0.05
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}